{{- $outer := . }}
{{- range $containers := (index .Values "packages" "azure-storage-backups" "containers") }}
  {{- with $outer }}
---
apiVersion: storage.azure.upbound.io/v1beta1
kind: Container
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ $containers.name }}
spec:
  forProvider:
    containerAccessType: private
    storageAccountName: {{ .Values.organization }}{{ .Values.project }}backups
  providerConfigRef:
    name: crossplane-azure-provider
  {{- end }}
{{- end }}