---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ .Values.packages.velero.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  cloud: {{ required "Secret is required for velero." .Values.packages.velero.credentials.credentials_b64 | quote }}
...
