{{- $outer := . }}
{{- range $conf := (index .Values "packages" "flexible-server-mysql" "configurations") }}
{{- with $outer }}
---
apiVersion: dbformysql.azure.upbound.io/v1beta1
kind: FlexibleServerConfiguration
metadata:
  annotations:
    crossplane.io/external-name: {{ $conf.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ .Release.Name }}-{{ $conf.name | replace "_" "-" }}
  namespace: {{ .Release.Namespace }}
spec:
  forProvider:
    resourceGroupName: {{ index .Values "packages" "flexible-server-mysql" "resourceGroupName" }}
    serverName: {{ index .Values "packages" "flexible-server-mysql" "name" }}
    value: {{ $conf.value | quote }}
  providerConfigRef:
    name: crossplane-azure-provider
{{- end }}
...
{{- end }}
